apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
  namespace: csml-beach
spec:
  containers:
    - name: shell
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      command: ["sleep"]
      args: ["infinity"]
      resources:
        requests:
          cpu: "1"
        limits:
          cpu: "1"
      volumeMounts:
        - name: csml-beach-storage
          mountPath: /mnt/data
  volumes:
    - name: csml-beach-storage
      persistentVolumeClaim:
        claimName: csml-beach-pvc
  restartPolicy: Never
