apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-test-git
  namespace: csml-beach
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: gpu-test
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
        securityContext:
          runAsUser: 0  # Run as root to ensure PVC write access
        env:
        - name: SCRIPT_NAME
          value: "gpu-test.py"
        command: ["sh", "-c"]
        args:
          - |
            git clone https://github.com/csml-beach/nrp.git /tmp/repo && \
            python /tmp/repo/scripts/$SCRIPT_NAME > /mnt/data/output_${SCRIPT_NAME}.txt
        volumeMounts:
        - name: csml-beach-storage
          mountPath: /mnt/data
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
            nvidia.com/gpu: "1"
          requests:
            memory: 2Gi
            cpu: "1"
            nvidia.com/gpu: "1"
      restartPolicy: Never
      volumes:
      - name: csml-beach-storage
        persistentVolumeClaim:
          claimName: csml-beach-pvc
  backoffLimit: 1
