apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csml-beach-pvc
  namespace: csml-beach
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
